# This is a workflow to deploy website to aliyun oss with Actions

name: oss-deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # insta npm
    - name: install
      run: npm install
    
    # build
    - name: build
      run: npm run build
      
    # Runs a set of commands using the runners shell
    - name: deploy
      uses: manyuanrong/setup-ossutil@v1.0
      with:
        # 填写Bucket所在地域的域名信息，可参考访问域名和数据中心。
        endpoint: oss-cn-beijing.aliyuncs.com
        # AccessKeyID
        access-key-id: ${{ secrets.OSS_AK }}
        # AccessKeySceret
        access-key-secret: ${{ secrets.OSS_SK }}
        # 非必配项，若采用STS临时授权方式访问OSS需要配置该项。stsToken生成方式参考临时访问凭证
        # sts-token: # optional, default is 
    - run: ossutil cp -rf .vuepress/dist oss://blog-ngy/
